apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: odf-preinstall-benchmark
  labels:
    app: odf-preinstall-benchmark
spec:
  selector:
    matchLabels:
      app: odf-preinstall-benchmark
  template:
    metadata:
      labels:
        app: odf-preinstall-benchmark
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: odf-benchmark
          image: quay.io/myathnal/odf-benchmarker:latest
          command: ["python", "benchmarker.py", "--resources", "/app/resources.json", "--metrics", "/app/metrics.json"
          ]
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: benchmark-config
              mountPath: /app/resources.json
              subPath: benchmark.json
            - name: host-dev
              mountPath: /dev
            - name: host-proc
              mountPath: /proc
            - name: host-sys
              mountPath: /sys
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            limits:
              cpu: "4"
              memory: "8Gi"
            requests:
              cpu: "2"
              memory: "4Gi"
      volumes:
        - name: benchmark-config
          configMap:
            name: benchmark-metrics
        - name: host-dev
          hostPath:
            path: /dev
        - name: host-proc
          hostPath:
            path: /proc
        - name: host-sys
          hostPath:
            path: /sys
